### ISSUE TITLE
QR-code-card doesn't render on the actual dashboard but renders in preview correctly

### ISSUE THREAD

**Issue by mitchsurp** [igor-panteleev/lovelace-qr-code-card#4]
I have a sensor that pre-fills text of a URL, and I'm attempting to use the entity function to generate it. 

<img width="901" alt="image" src="https://user-images.githubusercontent.com/19660494/184665316-2d9bfb3b-148c-4c5c-9537-2343e6672ffe.png">

`type: custom:qr-code-card
source: entity
title: 'Read More:'
entity: sensor.nytimes_headline_link`

But on clicking Save:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/19660494/184665437-71335fa8-573c-4536-bd1b-d00ca6bf7f52.png">

It works with text and wifi correctly, but it refuses to render with a sensor. It is not limited to this sensor, either. Is there a theme restriction I'm not aware of? Or something else I can try to determine if the issue is on my end? I have rebooted HA, reloaded the Lovelace UI, cleared my cache, used multiple machines and even downgraded versions of QR-code-card in HACS with no success.

**Comment by MtenHoorn** [comment]
I have the same problem when using entity.

**Comment by cg089** [comment]
Same problem here

**Comment by geertmeersman** [comment]
Hi, was someone able to solve it?

**Comment by geertmeersman** [comment]
In case someone would be interested, I have a small workaround until Igor fixes the issue :-)

```
type: custom:config-template-card
variables:
  WIFI_QR: states['sensor.wifi_qr'].state
  WIFI_TITLE: states['sensor.wifi_qr'].attributes.friendly_name
entities:
  - sensor.telenet_a082915_internet_wifi_qr
card:
  type: custom:qr-code-card
  source: text
  text: ${WIFI_QR}
  title: ${WIFI_TITLE}
```
